export const ENDPOINTS_CLIENTE = {
  listar: "/api/Cliente/listar",
  crear: "/api/Cliente/crear",
  obtener: "/api/Cliente/obtener",
  eliminar: "/api/Cliente/eliminar",
  editar: "/api/Cliente/editar",
  listaCorta: "/api/Cliente/listaCorta",
  listarTarifario: "/api/Tarifario/listar",
  crearTarifario: "/api/Tarifario/crear",
  editarTarifario: "/api/Tarifario/editar",
  eliminarTarifario: "/api/Tarifario/eliminar",
  obtenerTarifario: "/api/Tarifario/obtener",
  listaCortaTarifario: "/api/Tarifario/listaCorta",
  listarContactos: "/api/ClienteContacto/listar",
  crearContacto: "/api/ClienteContacto/crear",
  editarContacto: "/api/ClienteContacto/editar",
  eliminarContacto: "/api/ClienteContacto/eliminar",
  obtenerContacto: "/api/ClienteContacto/obtener",
} as const;
