export const ENDPOINTS_INFORME = {
  listar: "/api/Informe/listar",
  crear: "/api/Informe/crear",
  actualizarEstado: "/api/Informe/actualizarEstado",
  editar: "/api/Informe/editar",
  obtener: "/api/Informe/obtener",
  previsualizarDocumento: "/api/Informe/previsualizarDocumento",
  obtenerDocumento: "/api/Informe/obtenerDocumento",
  obtenerUrlPrefirmada: "/api/Informe/obtenerUrlPrefirmada",
  autocompletar: "/api/Informe/autocompletar",
  traducir: "/api/Informe/traducir",
  extraerDocumento: "/api/Informe/extraerDocumento",
  calcularBalanceTotalizado: "/api/Informe/calcularBalanceTotalizado",
  calcularBalanceDesagregado: "/api/Informe/calcularBalanceDesagregado",
  calcularBalanceBanco: "/api/Informe/calcularBalanceBanco",
  calcularBalanceSeguro: "/api/Informe/calcularBalanceSeguro",
  calcularBalanceTurquia: "/api/Informe/calcularBalanceTurquia",
} as const;
