import type { PedidoDetalleFacturaVerificacion } from "@maximilian/shared/types/verificacion-factura.type";

export const PESTANAS_DETALLE_PEDIDOS_FACTURA_VERIFICACION = [
  { id: "general", etiqueta: "General" },
  { id: "normal", etiqueta: "Normal" },
  { id: "express", etiqueta: "Express" },
  { id: "super-flash", etiqueta: "Super Flash" },
] as const;

export type PestanaDetallePedidosFacturaVerificacion =
  (typeof PESTANAS_DETALLE_PEDIDOS_FACTURA_VERIFICACION)[number]["id"];

export const CANTIDAD_PEDIDOS_DETALLE_FACTURA_VERIFICACION_POR_PAGINA = 5;

export const PEDIDOS_DETALLE_FACTURA_VERIFICACION_MOCK: PedidoDetalleFacturaVerificacion[] = [
  {
    idPedido: 401,
    tipo: "normal",
    investigarRazonSocialNombres: "Comercial Andina SAC",
    numeroReferencia: "EM202600801",
    pais: "Colombia",
    fechaSolicitud: "28/05/2026",
    fechaEnvio: "01/06/2026",
    tipoServicio: "Informe",
    precio: 35.0,
  },
  {
    idPedido: 402,
    tipo: "normal",
    investigarRazonSocialNombres: "Textiles Peru Norte EIRL",
    numeroReferencia: "EM202600804",
    pais: "Peru",
    fechaSolicitud: "29/05/2026",
    fechaEnvio: "02/06/2026",
    tipoServicio: "Informe",
    precio: 40.0,
  },
  {
    idPedido: 403,
    tipo: "normal",
    investigarRazonSocialNombres: "Agroindustrias Vega SAC",
    numeroReferencia: "EM202600806",
    pais: "Costa Rica",
    fechaSolicitud: "29/05/2026",
    fechaEnvio: "03/06/2026",
    tipoServicio: "Informe",
    precio: 45.5,
  },
  {
    idPedido: 404,
    tipo: "normal",
    investigarRazonSocialNombres: "Distribuidora Nortesol SRL",
    numeroReferencia: "EM202600809",
    pais: "Panama",
    fechaSolicitud: "01/06/2026",
    fechaEnvio: "05/06/2026",
    tipoServicio: "Informe",
    precio: 38.0,
  },
  {
    idPedido: 405,
    tipo: "normal",
    investigarRazonSocialNombres: "Consultora Prisma Legal SAC",
    numeroReferencia: "EM202600810",
    pais: "Mexico",
    fechaSolicitud: "01/06/2026",
    fechaEnvio: "05/06/2026",
    tipoServicio: "Informe",
    precio: 42.0,
  },
  {
    idPedido: 406,
    tipo: "normal",
    investigarRazonSocialNombres: "Editorial Letras Vivas SAC",
    numeroReferencia: "EM202600811",
    pais: "Colombia",
    fechaSolicitud: "01/06/2026",
    fechaEnvio: "05/06/2026",
    tipoServicio: "Informe",
    precio: 48.0,
  },
  {
    idPedido: 407,
    tipo: "express",
    investigarRazonSocialNombres: "Grupo Delta Import SAC",
    numeroReferencia: "EM202600812",
    pais: "Colombia",
    fechaSolicitud: "01/06/2026",
    fechaEnvio: "05/06/2026",
    tipoServicio: "Informe",
    precio: 75.0,
  },
  {
    idPedido: 408,
    tipo: "express",
    investigarRazonSocialNombres: "Inversiones Cusco EIRL",
    numeroReferencia: "EM202600815",
    pais: "Mexico",
    fechaSolicitud: "01/06/2026",
    fechaEnvio: "03/06/2026",
    tipoServicio: "Informe",
    precio: 80.0,
  },
  {
    idPedido: 409,
    tipo: "express",
    investigarRazonSocialNombres: "Logística Pacífico SAC",
    numeroReferencia: "EM202600816",
    pais: "Costa Rica",
    fechaSolicitud: "01/06/2026",
    fechaEnvio: "03/06/2026",
    tipoServicio: "Informe",
    precio: 68.0,
  },
  {
    idPedido: 410,
    tipo: "express",
    investigarRazonSocialNombres: "Farmacéutica Salud Total SA",
    numeroReferencia: "EM202600818",
    pais: "Nicaragua",
    fechaSolicitud: "01/06/2026",
    fechaEnvio: "03/06/2026",
    tipoServicio: "Informe",
    precio: 85.0,
  },
  {
    idPedido: 411,
    tipo: "express",
    investigarRazonSocialNombres: "Automotriz RutaSur SAC",
    numeroReferencia: "EM202600820",
    pais: "Estados Unidos",
    fechaSolicitud: "01/06/2026",
    fechaEnvio: "05/06/2026",
    tipoServicio: "Informe",
    precio: 72.0,
  },
  {
    idPedido: 412,
    tipo: "express",
    investigarRazonSocialNombres: "Importadora Estrella Andina SAC",
    numeroReferencia: "EM202600822",
    pais: "Republica Dominicana",
    fechaSolicitud: "01/06/2026",
    fechaEnvio: "03/06/2026",
    tipoServicio: "Informe",
    precio: 90.0,
  },
  {
    idPedido: 413,
    tipo: "super-flash",
    investigarRazonSocialNombres: "Minera Los Andes SA",
    numeroReferencia: "EM202600823",
    pais: "Mexico",
    fechaSolicitud: "01/06/2026",
    fechaEnvio: "03/06/2026",
    tipoServicio: "Informe",
    precio: 130.0,
  },
  {
    idPedido: 414,
    tipo: "super-flash",
    investigarRazonSocialNombres: "Constructora Horizonte SAC",
    numeroReferencia: "EM202600827",
    pais: "Panama",
    fechaSolicitud: "02/06/2026",
    fechaEnvio: "05/06/2026",
    tipoServicio: "Informe",
    precio: 145.0,
  },
  {
    idPedido: 415,
    tipo: "super-flash",
    investigarRazonSocialNombres: "Servicios Industriales Maipo SAC",
    numeroReferencia: "EM202600828",
    pais: "Colombia",
    fechaSolicitud: "02/06/2026",
    fechaEnvio: "05/06/2026",
    tipoServicio: "Informe",
    precio: 120.0,
  },
  {
    idPedido: 416,
    tipo: "super-flash",
    investigarRazonSocialNombres: "Comercial Frontera Verde SAC",
    numeroReferencia: "EM202600829",
    pais: "Honduras",
    fechaSolicitud: "02/06/2026",
    fechaEnvio: "05/06/2026",
    tipoServicio: "Informe",
    precio: 135.0,
  },
  {
    idPedido: 417,
    tipo: "super-flash",
    investigarRazonSocialNombres: "Grupo Manufacturero Zeta SA",
    numeroReferencia: "EM202600830",
    pais: "Colombia",
    fechaSolicitud: "02/06/2026",
    fechaEnvio: "05/06/2026",
    tipoServicio: "Informe",
    precio: 150.0,
  },
  {
    idPedido: 418,
    tipo: "super-flash",
    investigarRazonSocialNombres: "Distribuciones El Roble SAC",
    numeroReferencia: "EM202600831",
    pais: "Republica Dominicana",
    fechaSolicitud: "02/06/2026",
    fechaEnvio: "05/06/2026",
    tipoServicio: "Informe",
    precio: 125.0,
  },
];
